### PR TITLE
updates for compile on focal/noetic

### PR DESCRIPTION
**Pull request by davefeilseifer**

### CODE REVIEW

**Comment by davefeilseifer** [comment]
passes prerelease testing:

generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml   noetic default ubuntu focal amd64   --custom-repo     driver_common__custom-1:git:https://github.com/PR2-prime/driver_common.git:indigo-devel     --level 0   --output-dir ./

**Comment by davefeilseifer** [comment]
I don't know who handles pulls for this, but can @chadrockey help me out with this? Releasing driver_common will help with the release for prosilica_camera and wge100_driver

**Comment by davefeilseifer** [comment]
ping @chadrockey

**Comment by chadrockey** [comment]
Oops, sorry I get a ton of GitHub emails and miss the tags sometimes.  I think this repo is only commonly used for the PR2 systems.

Are you maintaining those other drivers?  Would you like to have maintainership of this one?

**Comment by davefeilseifer** [comment]
> Oops, sorry I get a ton of GitHub emails and miss the tags sometimes. I think this repo is only commonly used for the PR2 systems.
> 
> Are you maintaining those other drivers? Would you like to have maintainership of this one?

I'm happy to just have drivers_common added to the pr2-drivers team, and then I'll have access to merge the pull from there.

**Comment by chadrockey** [comment]
@davefeilseifer was that sufficient?  Hope it helps!  :)

**Comment by davefeilseifer** [comment]
> @davefeilseifer was that sufficient? Hope it helps! :)

thanks! that did it

**Pull request merged**
